name: Claude Automation

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:
    inputs:
      task:
        description: 'Task for Claude to perform'
        required: true
        default: 'Enhance the codebase'

jobs:
  claude-task:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'claude') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Claude CLI
      run: |
        pip install anthropic
        pip install requests
    
    - name: Run Claude Enhancement
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -c "
        import os
        import requests
        from anthropic import Anthropic
        
        # Basic Claude automation script
        client = Anthropic(api_key=os.environ['ANTHROPIC_API_KEY'])
        
        task = '''
        Enhance the Serendipity AI project:
        1. Update main.py with session management and better error handling
        2. Create modern responsive frontend in static/index.html  
        3. Update requirements.txt with proper dependencies
        4. Make it production-ready
        '''
        
        response = client.messages.create(
            model='claude-3-sonnet-20240229',
            max_tokens=4000,
            messages=[{
                'role': 'user', 
                'content': f'Please provide enhanced code for: {task}'
            }]
        )
        
        print('Claude response received!')
        print(response.content[0].text[:500])
        "
    
    - name: Comment on Issue
      if: github.event_name == 'issues'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🤖 Claude automation has started processing your request! Check the Actions tab for progress.'
          })
