name: Minimal Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test 1 - Basic Info
      run: |
        echo "✅ GitHub Actions is working"
        echo "Actor: ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"

    - name: Test 2 - Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Test 3 - File Operations
      run: |
        echo "Testing file operations..."
        echo "test content" > test.txt
        ls -la test.txt
        cat test.txt
        rm test.txt
        echo "✅ File operations work"

    - name: Test 4 - Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Test 5 - Anthropic Install
      run: |
        pip install anthropic
        python -c "import anthropic; print('✅ Anthropic installed')"

    - name: Test 6 - API Key Check
      run: |
        if [ -z "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
          echo "❌ ANTHROPIC_API_KEY not found"
          exit 1
        else
          echo "✅ ANTHROPIC_API_KEY exists"
          echo "Length: ${#ANTHROPIC_API_KEY}"
        fi
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    - name: Test 7 - Git Config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "✅ Git config set"

    - name: Test 8 - Branch Test
      run: |
        current=$(git branch --show-current)
        echo "Current branch: $current"
        git checkout -b test-branch-$$
        echo "✅ Branch creation works"
        git checkout $current
        git branch -D test-branch-$$
        echo "✅ Branch cleanup works"

    - name: Test 9 - Simple PR Test
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Test commit"
        branch: test-pr-branch
        title: "🧪 Test PR - Delete Me"
        body: "This is a test PR. Please delete it."
        delete-branch: true

    - name: Test 10 - Final Report
      if: always()
      run: |
        echo "🎯 All tests completed!"
        echo "If you see this, the workflow is working properly."
